version: "2"
options:
  verbose: false
syncs:
  template-rsync:
    src: '~/robot.dev/template/'
    dest: '/template'
    sync_host_ip: 'localhost'
    sync_host_port: 10800
    sync_strategy: 'rsync'
    sync_userid: '1000'
    sync_prefer: 'default'
    watch_excludes: ['.*/.git', '.idea', '.gitignore', '.swp']